# Generated by Django 2.2 on 2019-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('time_to_do', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(max_length=250)),
            ],
        ),
    ]
