# Generated by Django 2.2 on 2019-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190421_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=170)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='comments',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
