# Generated by Django 2.2 on 2019-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190421_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='actions', to='main.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=170),
        ),
    ]
