# Generated by Django 2.2 on 2019-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190421_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='time_to_do',
            new_name='time_to_do_hour',
        ),
        migrations.AddField(
            model_name='action',
            name='time_to_do_minute',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
