# Generated by Django 2.2 on 2019-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190424_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_to_do_hour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
