# Generated by Django 2.2 on 2019-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190425_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_to_do_hour',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='time_to_do_minute',
            field=models.IntegerField(),
        ),
    ]
