# Generated by Django 2.2 on 2019-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190425_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_to_do_hour',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
