# Generated by Django 2.2 on 2019-04-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190425_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_to_do_minute',
            field=models.IntegerField(default=0),
        ),
    ]
