# Generated by Django 2.2 on 2019-04-25 15:47

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190425_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='comments',
            new_name='description',
        ),
        migrations.AddField(
            model_name='action',
            name='image',
            field=models.ImageField(default='media/image/mac.jpg', upload_to=main.models.image_folder),
            preserve_default=False,
        ),
    ]
