# Generated by Django 2.2 on 2019-04-25 16:22

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190425_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.ImageField(upload_to=main.models.image_folder),
        ),
    ]
