# Generated by Django 2.2 on 2019-04-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190425_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time_should_be',
            field=models.IntegerField(default=1),
        ),
    ]
