# Generated by Django 2.2 on 2019-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_action_time_should_be'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_should_be',
            field=models.IntegerField(),
        ),
    ]
