# Generated by Django 2.2 on 2019-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190426_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='time_should_be',
        ),
        migrations.AddField(
            model_name='action',
            name='time_trigger',
            field=models.BooleanField(default=False),
        ),
    ]
