# Generated by Django 2.2 on 2019-04-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190426_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time_should_be_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='time_should_be_minute',
            field=models.IntegerField(default=0),
        ),
    ]
