# Generated by Django 2.2 on 2019-04-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190426_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_should_be_hour',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='time_should_be_minute',
            field=models.IntegerField(blank=True),
        ),
    ]
