# Generated by Django 2.2 on 2019-04-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190426_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_should_be_hour',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
