# Generated by Django 2.2 on 2019-04-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190426_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_should_be_hour',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='time_to_do_hour',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='time_to_do_minute',
            field=models.IntegerField(blank=True),
        ),
    ]
