# Generated by Django 2.2 on 2019-04-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190426_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='image',
        ),
    ]
