# Generated by Django 2.2 on 2019-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_action_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
