# Generated by Django 2.2 on 2019-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_category_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
